name:                d2js
version:             0.1.0.0
github:              "chrisnevers/d2js"
license:             BSD3
author:              "Christopher Nevers"
maintainer:          "cnevers@reach.sh"
copyright:           "2021 Christopher Nevers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/d2js#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- cmark
- text
- directory
- filepath

library:
  source-dirs: src

executables:
  d2js-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d2js

tests:
  d2js-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d2js
